const PlayersData = [
  { id: 66,
    name: "Rohit Sharma",
    score: 100,
    img: "img.svg",
  },
  { id: 19,
    name: "KL Rahul",
    score: 100,
    img: "img.svg",
  },
  { id:26,
    name: "Virat Kohli",
    score: 0,
    img: "img.svg",
  },
  { id:30,
    name: "Hardik Pandya",
    score: 80,
    img: "img.svg",
  },
  { id:40,
    name: "Rishabh Pant",
    score: 80,
    img: "img.svg",
  },
];
export default PlayersData;
